### PR TITLE
Added mysql host, usage of it and default value to be localhost

### PR DESCRIPTION
**Pull request by manuperezgo**
just a tiny contribution.

### CODE REVIEW

**Comment by arikogan** [comment]
Thanks @manuperezgo.
I think there should be a space between the -h and the host.
e.g. `-h $MYSQL_HOST"`
See [http://dev.mysql.com/doc/refman/5.7/en/connecting.html](http://dev.mysql.com/doc/refman/5.7/en/connecting.html)

**Comment by manuperezgo** [comment]
space between -h and the host is not needed, I can add it if you prefer, just let me know

**Comment by arikogan** [comment]
You are right @manuperezgo. Just please change the host to be 127.0.0.1 instead of localhost so it won't connect through socket instead of TCP. Thanks!

**Comment by manuperezgo** [comment]
@arikogan it has been changed, Cheers!

**Pull request closed without merging**
